### ISSUE TITLE
Blockquotes lack styling, existing blockquote usage is incorrect

### ISSUE THREAD

**Issue by hergaiety** [ember-learn/guides-source#1468]
# Problem Summary

1. Blockquotes are unstyled in the guide
2. Many guides currently utilize blockquotes in a semantically incorrect way

**Example _screenshot_ where the second paragraph is a blockquote:**

> <img width="766" alt="Screen Shot 2020-07-01 at 10 20 45 AM" src="https://user-images.githubusercontent.com/1664093/86272071-9dc8f180-bb93-11ea-9106-bb46e9eee0f2.png">
> 
> <cite><a href="https://github.com/ember-learn/guides-source/issues/new">As seen in the Testing Components guide</a></cite>

# Details

In markdown the `> ` indicates a `blockquote` html element.

```markdown
> Hello, I am a blockquote!
> <cite>Gaiety</cite>
```

> The HTML `<blockquote>` Element (or HTML Block Quotation Element) indicates that the enclosed text is an extended quotation... a text representation of the source can be given using the `<cite>` element.
> <cite>[MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote)</cite>

Therefore, we can conclude that we should be using `> ` in guides specifically when a quote is being used along with a reference to the source. Any place that uses `> ` that isn't a quote is incorrect and should be changed.

# Proposed Solution

## 1. Styling the Blockquote

We decide on a blockquote styling. Here's my proposed styling that uses colors and styles pulled from other elements within the guides:

```css
.chapter blockquote {
  font-family: serif;
  font-size: 85%;
  color: #4d4d4d;
  padding: 0.5em 0.75em;
  border: 1px solid #F8E7CF;
  border-radius: 2px;
}
.chapter blockquote :first-child {
  margin-top: 0;
}
.chapter blockquote :last-child {
  margin-bottom: 0;
}
```

Preview:

> <img width="820" alt="Screen Shot 2020-07-01 at 12 08 18 PM" src="https://user-images.githubusercontent.com/1664093/86272053-986ba700-bb93-11ea-8108-4f6a12a8288a.png">
> 
> <cite>As pulled from #1467</cite>

## 2. Changing existing blockquote instances

We go through existing guides (perhaps just in `guides/release`, although it'll be up to the learning team how far back we go) to address each instance of a blockquote to remove them, leave them, or change them to something else in markdown.

> ```bash
> git grep -n "^> "
> ```
> <cite>@ijlee2</cite>
